### ISSUE TITLE
Conditional Props with Deploy-time Eval

### ISSUE THREAD

**Issue by tveal** [ilayanambi86/serverless-plugin-resource-tagging#12]
**I'll create a pull request to skip applying resource tags in this scenario.** Documenting issue here for reference.

Issue: When an AWS resource has a root `Properties`-level CloudFormation conditional, this plugin still applies the `Tags` property, which breaks at deploy-time.

Sample in serverless.yml
```yml
provider:
  name: aws
  # ...
  stackTags:
    MyOrg:Name: github issue sample

custom:
  bucketProps:
    Fn::If:
      - IsOtherRegionDeployed
      - ${file(additional.yml):BucketProps.withReplication}
      - ${file(additional.yml):BucketProps.noReplication}

resources:
  # ...
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties: ${self:custom.bucketProps}
```

Sample in cloudformation-template-update-stack.json
```jsonc
"Bucket": {
  "Type": "AWS::S3::Bucket",
  "Properties": {
    "Fn::If": [ // CloudFormation conditional evaluated at deploy-time
      "IsOtherRegionDeployed",
      {
        // with replication...
      },
      {
        // no replication
      }
    ],
    "Tags": [ // breaks the CloudFormation deploy due to conditional Fn::If
      {
        "Key": "MyOrg:Name",
        "Value": "github issue sample"
      }
    ]
  }
},
```
