### ISSUE TITLE
Error if API Gateway Stage is not created

### ISSUE THREAD

**Issue by m-radzikowski** [ilayanambi86/serverless-plugin-resource-tagging#3]
With multi-stack repository we have ApiGateway created in one stack and used in other stacks. So the "API" stack looks like this:

```yaml
service: api

plugins:
  - serverless-plugin-resource-tagging

provider:
  name: aws
  stage: ${opt:stage}
  stackTags: ${file(../config.json):tags}

resources:
  Resources:

    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.baseName}
```

After deployment process fails with error:

>   Stage dev on RestApi xxxxxxxxxx was not found

This looks like the plugin find that stack contains API Gateway and tries to find the Stage in it, and fails if it does not exist. Instead, it should just ignore it and not throw an error.
