### ISSUE TITLE
Plugin does not support to Dynamo Tables

### ISSUE THREAD

**Issue by gautampambhar** [ilayanambi86/serverless-plugin-resource-tagging#4]
This plugin works for every supported AWS resource listed here except Dynamo Tables. Any workaround to make it work against Dyanamo Tables?

I am using this plugin under the provider section of serverless like below. 
```
plugins:
  - serverless-plugin-resource-tagging
  
provider:
  name: aws
  stackTags:
        STACK: "${self:service}"
        PRODUCT: "Produuct"
        PRODUCT_VERSION: "1.0"   
```
Although it works as expected with an S3 Bucket, CloudFormation, Kinesis, Lambda and API GATEWAYS.
